### ISSUE TITLE
about download .ptt .rnt files

### ISSUE THREAD

**Issue by felixlyd** [YulongNiu/ProGenome#1]
Hello Dr. Niu,
Recently I wrote some python scripts in order to download the `.ptt` `.rnt` file. But finally I cannot deal with it.
Could you help me?

**Comment by felixlyd** [comment]
Now I have figured out the relation between `.ptt` and `.gff` and the content in `.rnt` file(some RNA except mRNA). But I was still confused on some tags in the `.ptt` file. 
1. I found the tag named `COG` in the `.ptt` file, and it means [**Clusters of Orthologous Groups**]. I cannot figure out why there is a `COG` tag because rockhopper used the algorithm based on RNA-Seq instead of COG. 
2. I found the tag named `PID` in the `.ptt` and `.rnt` file. I cannot find out its mean on Google or NCBI. 

[**Clusters of Orthologous Groups**]: https://www.ncbi.nlm.nih.gov/COG/

**Comment by YulongNiu** [comment]
@GodInLove According to the [NCBI FTP FAQ](https://www.ncbi.nlm.nih.gov/genome/doc/ftpfaq/), *.ptt  and *.rnt files are replaced with the *_feature_table.txt.gz.

**Comment by YulongNiu** [comment]
@GodInLove I added some functions e.g. `ExtractPtt()` and `ExtractRnt()` in the version 0.06 to process *ptt and *rnt files. Please also check the [gist](https://gist.github.com/YulongNiu/3e51804cb170b603b9633bd1fc0c611c) for an example.

**Comment by GodInLove** [comment]
Thanks! But as far as I am concerned, if there is a GB_number([AP009048]), it cannot solve the problem when I input a NC_number.


[AP009048]:http://www.genome.jp/kegg-bin/show_organism?org=ecj
